import {useEffect,useState} from 'react';
import {api} from '../services/api';

export default function LineSettingsPage(){
 const[status,setStatus]=useState(null),[customers,setCustomers]=useState([]),[form,setForm]=useState({customer_id:'',text:''}),[message,setMessage]=useState(''),[error,setError]=useState(''),[sending,setSending]=useState(false);
 useEffect(()=>{Promise.all([api('/line/status'),api('/customers')]).then(([s,c])=>{setStatus(s);setCustomers(c.filter(x=>x.line_user_id))}).catch(e=>setError(e.message))},[]);
 const send=async e=>{e.preventDefault();setSending(true);setError('');setMessage('');try{await api('/line/push',{method:'POST',body:JSON.stringify(form)});setMessage('ส่งข้อความทดสอบแล้ว');setForm({...form,text:''})}catch(x){setError(x.message)}finally{setSending(false)}};
 return <section><div className="page-head"><div><h1>LINE ลูกค้า</h1><p>ผูก LINE ของลูกค้ากับข้อมูลลูกค้าในระบบ เพื่อส่งอัปเดตงานและรับแจ้งปัญหาให้ถูกคน</p></div></div>{error&&<div className="alert error">{error}</div>}{message&&<div className="alert success">{message}</div>}<div className="dashboard-grid"><div className="panel"><h2>สถานะ LINE Official Account</h2><div className="metric-row"><span>Channel Secret</span><strong>{status?.channel_secret?'พร้อม':'ยังไม่ตั้งค่า'}</strong></div><div className="metric-row"><span>Channel Access Token</span><strong>{status?.access_token?'พร้อม':'ยังไม่ตั้งค่า'}</strong></div><p className="muted">Webhook URL ที่ต้องตั้งใน LINE Developers</p><code>{status?.webhook_path||'/api/line/webhook'}</code><p className="muted">ลูกค้าที่ผูก LINE แล้ว {customers.length} ราย</p><div className="workflow-note"><b>ขั้นตอนใช้งานจริง</b><ol><li>ช่างเพิ่มลูกค้า/จุดติดตั้งจากหน้างาน</li><li>ระบบสร้างข้อความ “ลงทะเบียน …” เฉพาะลูกค้านั้น</li><li>ลูกค้าส่งข้อความนี้ใน LINE Official Account</li><li>ระบบผูก LINE เข้ากับลูกค้าอัตโนมัติ</li></ol></div></div><div className="panel"><h2>ส่งข้อความหาลูกค้า</h2><form onSubmit={send}><label className="form-field">ลูกค้าที่ผูก LINE แล้ว<select value={form.customer_id} onChange={e=>setForm({...form,customer_id:e.target.value})} required><option value="">-- เลือกลูกค้า --</option>{customers.map(x=><option key={x.customer_id} value={x.customer_id}>{x.customer_name}</option>)}</select></label><label className="form-field">ข้อความ<textarea rows="5" value={form.text} onChange={e=>setForm({...form,text:e.target.value})} required placeholder="เช่น แจ้งนัดหมาย หรือแจ้งสถานะงาน"/></label><div className="modal-actions"><button className="btn primary" disabled={sending||!status?.configured}>{sending?'กำลังส่ง...':'ส่งข้อความ LINE'}</button></div></form></div></div></section>;
}
