import {useEffect,useState} from 'react';
import {api} from '../services/api';

export default function LineSettingsPage(){
 const[status,setStatus]=useState(null),[customers,setCustomers]=useState([]),[form,setForm]=useState({customer_id:'',text:''}),[message,setMessage]=useState(''),[error,setError]=useState(''),[sending,setSending]=useState(false);
 useEffect(()=>{Promise.all([api('/line/status'),api('/customers')]).then(([s,c])=>{setStatus(s);setCustomers(c.filter(x=>x.line_user_id))}).catch(e=>setError(e.message))},[]);
 const send=async e=>{e.preventDefault();setSending(true);setError('');setMessage('');try{await api('/line/push',{method:'POST',body:JSON.stringify(form)});setMessage('ส่งข้อความทดสอบแล้ว');setForm({...form,text:''})}catch(x){setError(x.message)}finally{setSending(false)}};
 return <section><div className="page-head"><div><h1>LINE Messaging API</h1><p>รับแจ้งปัญหาจากลูกค้าและทดสอบส่งข้อความจากระบบ</p></div></div>{error&&<div className="alert error">{error}</div>}{message&&<div className="alert success">{message}</div>}<div className="dashboard-grid"><div className="panel"><h2>สถานะการเชื่อมต่อ</h2><div className="metric-row"><span>Channel secret</span><strong>{status?.channel_secret?'พร้อม':'ยังไม่ตั้งค่า'}</strong></div><div className="metric-row"><span>Access token</span><strong>{status?.access_token?'พร้อม':'ยังไม่ตั้งค่า'}</strong></div><p className="muted">Webhook path</p><code>{status?.webhook_path||'/api/line/webhook'}</code><p className="muted">ลูกค้าที่ผูก LINE แล้ว {customers.length} ราย</p></div><div className="panel"><h2>ส่งข้อความทดสอบ</h2><form onSubmit={send}><label className="form-field">ลูกค้า<select value={form.customer_id} onChange={e=>setForm({...form,customer_id:e.target.value})} required><option value="">-- เลือกลูกค้าที่ผูก LINE --</option>{customers.map(x=><option key={x.customer_id} value={x.customer_id}>{x.customer_name}</option>)}</select></label><label className="form-field">ข้อความ<textarea rows="5" value={form.text} onChange={e=>setForm({...form,text:e.target.value})} required placeholder="ข้อความที่ต้องการส่งถึงลูกค้า"/></label><div className="modal-actions"><button className="btn primary" disabled={sending||!status?.configured}>{sending?'กำลังส่ง...':'ส่งข้อความ LINE'}</button></div></form></div></div></section>;
}
