import {useState} from 'react';
import {api} from '../services/api';

export default function DeviceRepairForm({job,item,onReload,onError}){
 const[editing,setEditing]=useState(false),[saving,setSaving]=useState(false);
 const[form,setForm]=useState({...item,replacement_device_id:item.replacement_device_id||''});
 const editable=job.job_status==='in_progress';
 const save=async()=>{setSaving(true);try{await api(`/jobs/${job.job_id}/problem-devices/${item.problem_device_id}`,{method:'PUT',body:JSON.stringify(form)});setEditing(false);await onReload()}catch(x){onError(x.message)}finally{setSaving(false)}};
 const remove=async()=>{if(!confirm(`ลบรายการซ่อม ${item.serial_number} ใช่ไหม?`))return;try{await api(`/jobs/${job.job_id}/problem-devices/${item.problem_device_id}`,{method:'DELETE'});await onReload()}catch(x){onError(x.message)}};
 if(editing)return <div className="repair-editor">
  <div className="editor-title"><b>แก้ไข {item.model_name}</b><button onClick={()=>setEditing(false)}>×</button></div>
  <div className="form-grid"><label>อุปกรณ์<select value={form.device_id} onChange={e=>setForm({...form,device_id:e.target.value})}>{job.devices.map(device=><option value={device.device_id} key={device.device_id}>{device.model_name} · {device.serial_number}</option>)}</select></label><label>วิธีดำเนินการ<select value={form.repair_method} onChange={e=>setForm({...form,repair_method:e.target.value,replacement_device_id:e.target.value==='repair'?'':form.replacement_device_id})}><option value="repair">ซ่อม</option><option value="replace">เปลี่ยน</option></select></label>{form.repair_method==='replace'&&<label className="wide">อุปกรณ์ทดแทน<select required value={form.replacement_device_id} onChange={e=>setForm({...form,replacement_device_id:e.target.value})}><option value="">-- เลือกอุปกรณ์ทดแทน --</option>{job.devices.filter(device=>String(device.device_id)!==String(form.device_id)).map(device=><option value={device.device_id} key={device.device_id}>{device.model_name} · {device.serial_number}</option>)}</select></label>}<label className="wide">อาการที่ตรวจพบ<textarea required value={form.device_problem_detail||''} onChange={e=>setForm({...form,device_problem_detail:e.target.value})}/></label><label className="wide">สิ่งที่ดำเนินการ<textarea required value={form.device_action_detail||''} onChange={e=>setForm({...form,device_action_detail:e.target.value})}/></label></div>
  <div className="editor-actions"><button className="secondary" onClick={()=>setEditing(false)}>ยกเลิก</button><button className="primary" disabled={saving} onClick={save}>{saving?'กำลังบันทึก...':'บันทึกการแก้ไข'}</button></div>
 </div>;
 return <div className="repair-record"><div className="repair-record-head"><div><b>{item.model_name}</b><small>SN: {item.serial_number}</small></div><span>{item.repair_method==='repair'?'ซ่อม':'เปลี่ยนอุปกรณ์'}</span></div><dl><div><dt>อาการที่ตรวจพบ</dt><dd>{item.device_problem_detail||'-'}</dd></div><div><dt>การดำเนินการ</dt><dd>{item.device_action_detail||'-'}</dd></div>{item.repair_method==='replace'&&<div><dt>เครื่องทดแทน</dt><dd>{item.replacement_serial||'-'}</dd></div>}</dl>{editable&&<div className="record-actions"><button onClick={()=>setEditing(true)}>แก้ไขรายละเอียด</button><button className="danger-action" onClick={remove}>ลบ</button></div>}</div>;
}
